### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ebouchut** [ebouchut/learn-git#1]
- [ ] git added / deleted / removed / modified
- [ ] Should rather use a recipe of workflows on how to do things using git, rather than a boring list of commands and how to use them
- [ ] Configuration (3 layers: system, global, local), define user.email in global git config and override it in local git config
- [x] gitignore
- [x] Aliases
- [x] History
- [x] Remote 
- [x] Branch: Creating a branch after the fact
- [x] Tag
- [ ] Naming Convention
- [ ] Workflow
- [ ] The 3 trees (repository, staging area, working directory)
- [ ] git reset
- [ ] Stash -u
- [x] Commit with 3 parents (<= git stash -u) refs/stash^1 is the working dir, refs/stash^2 is the index, refs/stash^3 is the unstashed files
- [ ] [gh](https://cli.github.com/) Github CLI
